### ISSUE TITLE
New installation problem

### ISSUE THREAD

**Issue by shaihi** [robotican/armadillo2#2]
Just finished the fresh install of Ubuntu 16.04.3 + Ros Kinetic + Armadillo2 from latest branch and running `roslaunch armadillo2 armadillo2.launch gazebo:=true` and I get errors:

> ERROR: cannot launch node of type [armadillo2_services/armadillo2_services_node]: can't locate node [armadillo2_services_node] in package [armadillo2_services]
> ERROR: cannot launch node of type [espeak_ros/espeak_node]: can't locate node [espeak_node] in package [espeak_ros]
> .
> .
> .
> [FATAL] [1519340760.579920600, 0.336000000]: Failed to create robot simulation interface loader: Could not find library corresponding to plugin gazebo_ros_control/Armadillo2RobotHWSim. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
> 

Attaching log of run and log of `Catkin_make`
[log-2.txt](https://github.com/robotican/armadillo2/files/1756156/log-2.txt)
[log.txt](https://github.com/robotican/armadillo2/files/1756157/log.txt)

**Comment by elhayra** [comment]
I just tried to replicate the issue by installing the package on a fresh Ubuntu installation, but everything works with no errors. We also tested this installation script on couple of different PCs, and it  works for all of them.
It seems like something went wrong during the installation process.
Despite the fact that the error points on some problem with libfreenect build, try running gazebo as stand alone, is it running OK? After fresh installation it is recommended to run Gazebo first before trying to load it with our main launch file (because Gazebo needs to download some files from the internet).

**Anyway, performing a clean installation should solve your issue. Follow the instructions [here](http://wiki.ros.org/armadillo2/Tutorials/Installation)**

Please let me know if it works for you.

**Comment by shaihi** [comment]
`sudo rm-fr armadillo2` and then pulling it a new and running setup.sh worked
